spring.application.name=costflow
spring.datasource.url=jdbc:postgresql://localhost:5432/costflow
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true